### 变量设置 (可选，方便以后改)
#网关端口(9000)
@host = http://localhost:9000

### 测试登录ls
POST {{host}}/im-auth/auth/login
Content-Type: application/x-www-form-urlencoded

username=ls&password=12345

### 测试拉取历史聊天记录
GET {{host}}/im-server/chat/history?friendId=2039190026355220482
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIwMzkxOTAwNDc4NzYxOTQzMDYsInVzZXJuYW1lIjoibHMiLCJzdWIiOiJscyIsImlhdCI6MTc3NTQ3MDIyNywiZXhwIjoxNzc1NTU2NjI3fQ.vjqtEh4uQEyGddxJf_HLa3E9AD41VpN5MiUFo9SyIJc