### 变量设置 (可选，方便以后改)
@host = http://localhost:9000

# ==========================================
# 场景 1: 正常注册一个新用户
# ==========================================
POST {{host}}/im-auth/auth/register
Content-Type: application/x-www-form-urlencoded

username=ww&password=12345

###

# ==========================================
# 场景 2: 再次注册相同的用户 (预期报错)
# ==========================================
POST {{host}}/im-auth/auth/register
Content-Type: application/x-www-form-urlencoded

username=ww&password=12345

###
# ==========================================
# 场景 3: 用户登录 (获取 Token)
# ==========================================
POST {{host}}/im-auth/auth/login
Content-Type: application/x-www-form-urlencoded

username=zs&password=12345
###

POST {{host}}/im-auth/auth/login
Content-Type: application/x-www-form-urlencoded

username=ls&password=12345

###
# 测试好友列表（zs的）
GET {{host}}/im-auth/friend/list
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIwMzkxOTAwMjYzNTUyMjA0ODIsInVzZXJuYW1lIjoienMiLCJzdWIiOiJ6cyIsImlhdCI6MTc3NTAyMTgwOCwiZXhwIjoxNzc1MTA4MjA4fQ.NJVHKQrrqsLK-_czC2XNllc-JOQrotvuxcgiv-z_bgg

###
# 测试好友列表（ls的）
GET {{host}}/im-auth/friend/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIwMzkxOTAwNDc4NzYxOTQzMDYsInVzZXJuYW1lIjoibHMiLCJzdWIiOiJscyIsImlhdCI6MTc3NTMwODUyMSwiZXhwIjoxNzc1Mzk0OTIxfQ.5lvqeoNoH__9BQocOAnXExqHQHqBCdeU381MZU1HqSA

###
# 测试搜寻功能
GET {{host}}/im-auth/friend/search?username=ls
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIwMzg4MjIzMzY2ODM5MDA5MzAsInVzZXJuYW1lIjoienMiLCJzdWIiOiJ6cyIsImlhdCI6MTc3NDkyOTY3NSwiZXhwIjoxNzc1MDE2MDc1fQ.0nI5P9XC8sFpWcNtE5XUK4J0qEf-V-qvo2rIMfeVxRo

###
# 测试添加好友
POST {{host}}/im-auth/friend/add
# ls加ww
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIwMzkxOTAwNDc4NzYxOTQzMDYsInVzZXJuYW1lIjoibHMiLCJzdWIiOiJscyIsImlhdCI6MTc3NTAyMTg0MiwiZXhwIjoxNzc1MTA4MjQyfQ.YGOyowXfOjtHuv-naTfggVdiD_IY4YksgnqpCAX_j3M
Content-Type: application/x-www-form-urlencoded

targetUserId=2039190076783337474

###
POST {{host}}/im-auth/friend/add
# ls加zs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIwMzkxOTAwNDc4NzYxOTQzMDYsInVzZXJuYW1lIjoibHMiLCJzdWIiOiJscyIsImlhdCI6MTc3NTAyMTg0MiwiZXhwIjoxNzc1MTA4MjQyfQ.YGOyowXfOjtHuv-naTfggVdiD_IY4YksgnqpCAX_j3M
Content-Type: application/x-www-form-urlencoded

targetUserId=2039190026355220482

###
POST {{host}}/im-auth/friend/add
# zs加ww
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIwMzg4MjIzMzY2ODM5MDA5MzAsInVzZXJuYW1lIjoienMiLCJzdWIiOiJ6cyIsImlhdCI6MTc3NDk1OTkzNiwiZXhwIjoxNzc1MDQ2MzM2fQ.3WogWB8ReBF36jr3BtP4pEp_dehT5hPo47v_CSiiDPg
Content-Type: application/x-www-form-urlencoded

targetUserId=2038888113604734977

###