server:
  port: 9002 # Spring Boot 的 HTTP 端口 (Gateway:9000, Auth:9001, Spring Boot 内置的 Web 服务器:9002)

spring:
  application:
    name: im-server # 注册到 Nacos 的名字
  servlet:
    multipart:
      max-file-size: 100MB      # 单个文件最大限制，放宽到 10MB
      max-request-size: 100MB   # 整个请求最大限制
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: localhost          # Redis server host
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # localhost:8800，库名 im_core
    url: jdbc:mysql://localhost:8800/im_core?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

# 日志
logging:
  level:
    root: INFO # 整个 Spring Boot 框架底层的日志保持 INFO，不然控制台会被刷爆
    com.graduation.im: DEBUG # 把你自己的代码包路径设为 DEBUG

# 自定义配置：Netty 的 WebSocket 端口
im:
  server:
    port: 9003           # 真正聊天的端口
    websocket-path: /im  # WebSocket 的访问路径，如 ws://localhost:9003/im

# MyBatis Plus 配置 (打印 SQL 日志，方便调试)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MinIO 配置
minio:
  endpoint: http://localhost:19000  # API 端口！千万别写成控制台的 19001
  access-key: admin
  secret-key: admin12345
  bucket-name: im-chat


